### ISSUE TITLE
Disposing of the proxy on a Bluetooth disconnect can result in an exception

### ISSUE THREAD

**Issue by adein** [smartdevicelink/sdl_android#21]
Our recommended service management practice is to stop the AppLink service on a Bluetooth disconnect (ACL_DISCONNECTED) and dispose of the proxy (if it isn't null).  However, the SDK also internally tries to dispose/recycle the proxy when it observes the same disconnect.

Some comments from a thread on the Ford Developer forums:

> When I turn off bluetooth in my phone, I get this exception from the SyncProxyALM. It appears as though it is attempting to read after the BT transport is closed. Is this a bug or am I doing something wrong? I am stopping my service (and disposing off the proxy object) when the BT state changes to "turning_off" or if "acl_disconnected" is received.

```
11-07 22:05:15.941: W/System.err(32154): java.io.IOException: read failed, socket might closed or timeout, read ret: -1 
11-07 22:05:15.941: W/System.err(32154): at android.bluetooth.BluetoothSocket.readAll(BluetoothSocket.java:492) 
11-07 22:05:15.951: W/System.err(32154): at android.bluetooth.BluetoothSocket.waitSocketSignal(BluetoothSocket.java:469) 
11-07 22:05:15.991: W/System.err(32154): at android.bluetooth.BluetoothSocket.accept(BluetoothSocket.java:393) 
11-07 22:05:15.991: W/System.err(32154): at android.bluetooth.BluetoothServerSocket.accept(BluetoothServerSocket.java:131) 
11-07 22:05:15.991: W/System.err(32154): at android.bluetooth.BluetoothServerSocket.accept(BluetoothServerSocket.java:117) 
11-07 22:05:15.991: W/System.err(32154): at com.ford.syncV4.transport.BTTransport$TransportReaderThread.acceptConnection(BTTransport.java:219) 
11-07 22:05:16.011: W/System.err(32154): at com.ford.syncV4.transport.BTTransport$TransportReaderThread.run(BTTransport.java:302) 
11-07 22:05:16.031: W/System.err(32154): java.io.IOException: read failed, socket might closed or timeout, read ret: -1 
11-07 22:05:16.031: W/System.err(32154): at android.bluetooth.BluetoothSocket.readAll(BluetoothSocket.java:492) 
11-07 22:05:16.031: W/System.err(32154): at android.bluetooth.BluetoothSocket.waitSocketSignal(BluetoothSocket.java:469) 
11-07 22:05:16.041: W/System.err(32154): at android.bluetooth.BluetoothSocket.accept(BluetoothSocket.java:393) 
11-07 22:05:16.041: W/System.err(32154): at android.bluetooth.BluetoothServerSocket.accept(BluetoothServerSocket.java:131) 
11-07 22:05:16.041: W/System.err(32154): at android.bluetooth.BluetoothServerSocket.accept(BluetoothServerSocket.java:117) 
11-07 22:05:16.041: W/System.err(32154): at com.ford.syncV4.transport.BTTransport$TransportReaderThread.acceptConnection(BTTransport.java:219) 
11-07 22:05:16.041: W/System.err(32154): at com.ford.syncV4.transport.BTTransport$TransportReaderThread.run(BTTransport.java:302) 
```
> - praneetloke

</br>
> I am having the same issue. When I get ACL_DISCONNECTED I clean up by calling disposeSyncProxy (base off the sample code provided). Quite often this results in the following exception: 

```
2.2: Transport failure: Failed to read from Bluetooth transport. java.io.IOException: bt socket closed, read return: -1 
android.bluetooth.BluetoothSocket.read(BluetoothSocket.java:429) 
android.bluetooth.BluetoothInputStream.read(BluetoothInputStream.java:96) 
java.io.InputStream.read(InputStream.java:162) com.ford.syncV4.transport.BTTransport$TransportReaderThread.readFromTransport(BTTransport.java:364) 
com.ford.syncV4.transport.BTTransport$TransportReaderThread.run(BTTransport.java:405) 
```

>This hangs my call to dispose so the rest of my application specific cleanup code doesn't get called. It seems like my only other option at this point is call dispose on a new thread and let it crash while my calling thread will continue to clean up other code.
> - rebutl

**Comment by justinjdickow** [comment]
Could not reproduce in current library version
