### ISSUE TITLE
SDL PROXY Closes ANDROID

### ISSUE THREAD

**Issue by NDNELSON** [smartdevicelink/sdl_android#291]
I am developing an app for android and ford cars. I was using the applink library 2.0.

My apps works fine and it did not disconnect from the car system. I decided to update to 4.0 sdl library, but i have had a single problem . AFter single minutes the proxy closes and the app losses conection from the car system . My app consumes from 40bm to 110mb of ram. I am testing in samsung galaxy s6a nd my car register as TDK is a ford fiesta 2016
 titanium.
My code is based from hello sdl project.
This is my log file:
```
02-26 10:58:27.079    8809-8879/com.ford.autolink W/System.err﹕ java.io.IOException: read failed, socket might closed or timeout, read ret: -1
02-26 10:58:27.081    8809-8879/com.ford.autolink W/System.err﹕ at android.bluetooth.BluetoothSocket.readAll(BluetoothSocket.java:586)
02-26 10:58:27.081    8809-8879/com.ford.autolink W/System.err﹕ at android.bluetooth.BluetoothSocket.waitSocketSignal(BluetoothSocket.java:563)
02-26 10:58:27.081    8809-8879/com.ford.autolink W/System.err﹕ at android.bluetooth.BluetoothSocket.accept(BluetoothSocket.java:418)
02-26 10:58:27.081    8809-8879/com.ford.autolink W/System.err﹕ at android.bluetooth.BluetoothServerSocket.accept(BluetoothServerSocket.java:130)
02-26 10:58:27.081    8809-8879/com.ford.autolink W/System.err﹕ at android.bluetooth.BluetoothServerSocket.accept(BluetoothServerSocket.java:116)
02-26 10:58:27.081    8809-8879/com.ford.autolink W/System.err﹕ at com.smartdevicelink.transport.BTTransport$TransportReaderThread.acceptConnection(BTTransport.java:338)
02-26 10:58:27.081    8809-8879/com.ford.autolink W/System.err﹕ at com.smartdevicelink.transport.BTTransport$TransportReaderThread.run(BTTransport.java:421)
02-26 10:58:27.107    8809-8879/com.ford.autolink W/System.err﹕ java.io.IOException: read failed, socket might closed or timeout, read ret: -1
02-26 10:58:27.107    8809-8879/com.ford.autolink W/System.err﹕ at android.bluetooth.BluetoothSocket.readAll(BluetoothSocket.java:586)
02-26 10:58:27.107    8809-8879/com.ford.autolink W/System.err﹕ at android.bluetooth.BluetoothSocket.waitSocketSignal(BluetoothSocket.java:563)
02-26 10:58:27.107    8809-8879/com.ford.autolink W/System.err﹕ at android.bluetooth.BluetoothSocket.accept(BluetoothSocket.java:418)
02-26 10:58:27.107    8809-8879/com.ford.autolink W/System.err﹕ at android.bluetooth.BluetoothServerSocket.accept(BluetoothServerSocket.java:130)
02-26 10:58:27.107    8809-8879/com.ford.autolink W/System.err﹕ at android.bluetooth.BluetoothServerSocket.accept(BluetoothServerSocket.java:116)
02-26 10:58:27.107    8809-8879/com.ford.autolink W/System.err﹕ at com.smartdevicelink.transport.BTTransport$TransportReaderThread.acceptConnection(BTTransport.java:338)
02-26 10:58:27.107    8809-8879/com.ford.autolink W/System.err﹕ at com.smartdevicelink.transport.BTTransport$TransportReaderThread.run(BTTransport.java:421)
02-26 10:58:27.126    8809-8809/com.ford.autolink I/applinkmodo﹕ false
02-26 10:58:27.126    8809-8809/com.ford.autolink I/applinkmodo﹕ false
02-26 10:58:37.277    8809-8809/com.ford.autolink I/SDL Service﹕ Trying to start proxy
02-26 10:58:37.277    8809-8809/com.ford.autolink I/SDL Service﹕ Starting SDL Proxy
02-26 10:58:37.285    8809-8809/com.ford.autolink W/BluetoothAdapter﹕ getBluetoothService() called with no BluetoothManagerCallback
02-26 10:58:37.553    8809-8809/com.ford.autolink I/disp﹕ SYNC
02-26 10:58:51.119   8809-10427/com.ford.autolink I/SdlProxy﹕ SDL Proxy Version: 4.0.0-Android
02-26 10:58:51.809   8809-10427/com.ford.autolink I/SDL Service﹕ Permision changed: com.smartdevicelink.proxy.rpc.OnPermissionsChange@359a757a
02-26 10:58:51.818   8809-10427/com.ford.autolink I/SDL Service﹕ HMI_BACKGROUND
02-26 10:58:51.819   8809-10427/com.ford.autolink I/applinkmodo﹕ true
02-26 10:58:51.997   8809-10427/com.ford.autolink I/SDL Service﹕ OnSystemRequest notification from SDL: com.smartdevicelink.proxy.rpc.OnSystemRequest@261fd634
02-26 10:58:52.456   8809-10543/com.ford.autolink I/System.out﹕ propertyValue:false
02-26 10:58:58.158   8809-10543/com.ford.autolink I/sendOnSystemRequestToUrl﹕ sent to sdl
02-26 10:59:00.406   8809-10427/com.ford.autolink I/applinkmodo﹕ true
02-26 10:59:00.407   8809-10427/com.ford.autolink I/Lenguaje display﹕ ES-MX
02-26 10:59:00.407   8809-10427/com.ford.autolink I/Lenguaje voz﹕ ES-MX
02-26 10:59:00.418   8809-10427/com.ford.autolink I/DISPALYCAPABILITIES:﹕ NO ES NULL
02-26 10:59:00.427   8809-10427/com.ford.autolink I/Tipo Display:﹕ GEN3_8-INCH
02-26 10:59:00.428   8809-10427/com.ford.autolink I/DISPALYCAPABILITIES:﹕ true
02-26 10:59:00.428   8809-10427/com.ford.autolink I/DISPALYCAPABILITIES:﹕ SI soporta graficos
02-26 10:59:00.437   8809-10427/com.ford.autolink I/Hora Actual﹕ 10 de la mañana con 59 minutoss.
02-26 10:59:00.449   8809-10427/com.ford.autolink I/Mañana﹕ 2016/1/27
02-26 10:59:00.776   8809-10427/com.ford.autolink I/Timeline﹕ Timeline: Activity_launch_request id:com.ford.autolink time:67337775
02-26 10:59:00.786   8809-10427/com.ford.autolink I/SDL Service﹕ onListFilesResponse from SDL
02-26 10:59:00.891   8809-10427/com.ford.autolink I/SDL Service﹕ Show response from SDL: SUCCESS Info: null
02-26 10:59:00.918   8809-10427/com.ford.autolink I/SDL Service﹕ onPutFileResponse from SDL
02-26 10:59:00.922    8809-8929/com.ford.autolink I/MaliEGL﹕ [Mali]window_type=1, is_framebuffer=0, errnum = 0
02-26 10:59:00.922    8809-8929/com.ford.autolink I/MaliEGL﹕ [Mali]surface->num_buffers=4, surface->num_frames=3, win_min_undequeued=1
02-26 10:59:00.922    8809-8929/com.ford.autolink I/MaliEGL﹕ [Mali]max_allowed_dequeued_buffers=3
02-26 10:59:00.955    8809-8809/com.ford.autolink I/Timeline﹕ Timeline: Activity_idle id: android.os.BinderProxy@2354b4c4 time:67337954
02-26 10:59:00.993   8809-10427/com.ford.autolink I/SDL Service﹕ onPutFileResponse from SDL
02-26 10:59:01.209   8809-10427/com.ford.autolink I/SDL Service﹕ onPutFileResponse from SDL
02-26 10:59:01.230   8809-10427/com.ford.autolink I/SDL Service﹕ onPutFileResponse from SDL
02-26 10:59:01.364   8809-10427/com.ford.autolink I/SDL Service﹕ onPutFileResponse from SDL
02-26 10:59:01.451   8809-10427/com.ford.autolink I/SDL Service﹕ onPutFileResponse from SDL
02-26 10:59:01.568   8809-10427/com.ford.autolink I/SDL Service﹕ onPutFileResponse from SDL
02-26 10:59:01.640   8809-10427/com.ford.autolink I/SDL Service﹕ onPutFileResponse from SDL
02-26 10:59:01.878   8809-10427/com.ford.autolink I/SDL Service﹕ SpeakCommand response from SDL: SUCCESS Info: null
02-26 10:59:01.878   8809-10427/com.ford.autolink I/Speak Response:﹕ SUCCESS
02-26 10:59:01.928   8809-10427/com.ford.autolink I/SDL Service﹕ onPutFileResponse from SDL
02-26 10:59:01.988   8809-10427/com.ford.autolink I/SDL Service﹕ SetAppIcon response from SDL: SUCCESS Info: null
02-26 10:59:02.008   8809-10427/com.ford.autolink I/SDL Service﹕ onPutFileResponse from SDL
02-26 10:59:03.239   8809-10427/com.ford.autolink I/SDL Service﹕ AddCommand response from SDL: SUCCESS
02-26 10:59:03.241   8809-10427/com.ford.autolink I/SDL Service﹕ OnHashChange notification from SDL: com.smartdevicelink.proxy.rpc.OnHashChange@1a5be673
02-26 10:59:03.243   8809-10427/com.ford.autolink I/SDL Service﹕ AddCommand response from SDL: SUCCESS
02-26 10:59:03.244   8809-10427/com.ford.autolink I/SDL Service﹕ OnHashChange notification from SDL: com.smartdevicelink.proxy.rpc.OnHashChange@294a5930
02-26 10:59:18.050   8809-10427/com.ford.autolink I/SDL Service﹕ SpeakCommand response from SDL: SUCCESS Info: null
02-26 10:59:18.051   8809-10427/com.ford.autolink I/Speak Response:﹕ SUCCESS
02-26 11:00:35.114    8809-8826/com.ford.autolink W/ResourcesManager﹕ Asset path '/system/framework/com.google.android.maps.jar' does not exist or contains no resources.
02-26 11:00:35.122    8809-8826/com.ford.autolink I/notimensaje﹕ NOMBRE
02-26 11:00:35.123    8809-8826/com.ford.autolink I/notimensaje﹕ whatsinbox
02-26 11:00:35.124    8809-8826/com.ford.autolink I/notimensaje﹕ alerta Es contacto
02-26 11:00:50.499   8809-10427/com.ford.autolink I/SDL Service﹕ OnButtonEvent notification from SDL: com.smartdevicelink.proxy.rpc.OnButtonEvent@2db3d85c
02-26 11:00:50.608   8809-10427/com.ford.autolink I/SDL Service﹕ OnButtonEvent notification from SDL: com.smartdevicelink.proxy.rpc.OnButtonEvent@34a75765
02-26 11:00:50.615   8809-10427/com.ford.autolink I/SDL Service﹕ OnButtonPress notification from SDL: com.smartdevicelink.proxy.rpc.OnButtonPress@24ff2c3a
02-26 11:00:50.618   8809-10427/com.ford.autolink I/Boton presionado:﹕ CUSTOM_BUTTON
02-26 11:00:50.632   8809-10427/com.ford.autolink I/SDL Service﹕ Alert response from SDL: SUCCESS Info: null
02-26 11:00:53.869   8809-10427/com.ford.autolink I/SDL Service﹕ HMI_BACKGROUND
02-26 11:01:37.373    8809-8809/com.ford.autolink I/applinkmodo﹕ false
02-26 11:01:37.404    8809-8809/com.ford.autolink I/applinkmodo﹕ false
02-26 11:01:37.527    8809-8929/com.ford.autolink I/MaliEGL﹕ [Mali]window_type=1, is_framebuffer=0, errnum = 0
02-26 11:01:37.527    8809-8929/com.ford.autolink I/MaliEGL﹕ [Mali]surface->num_buffers=4, surface->num_frames=3, win_min_undequeued=1
02-26 11:01:37.527    8809-8929/com.ford.autolink I/MaliEGL﹕ [Mali]max_allowed_dequeued_buffers=3
02-26 11:01:37.607    8809-8809/com.ford.autolink I/Timeline﹕ Timeline: Activity_idle id: android.os.BinderProxy@ea55d35 time:67494606
```
Could anyone helpme please?

**Comment by joeygrover** [comment]
Not an issue with the library, should refer to the Slack channel for more help on integrating the library.
