### ISSUE TITLE
When disconnecting SDL Core, SDL Router sometimes crashes in TransportBroker

### ISSUE THREAD

**Issue by jthrun** [smartdevicelink/sdl_android#363]
A WeakReference is kept to the TransportBroker instance in the ClientHandler in TransportBroker class.  The ClientHandler.handleMessage() checks for null but only logs an error message, later resulting in a NullPointerException crash of SDL Router.  This can happen when stopping the SDL Core connection (power-off HU).

The exception is happening here: https://github.com/smartdevicelink/sdl_android/blob/develop/sdl_android_lib/src/com/smartdevicelink/transport/TransportBroker.java#L155

Here is the log messages and stack trace that I'm getting:

```
11-10 12:37:09.595  4288 12355 I SdlTransportBroker: Attempting to unregister with Sdl Router Service
11-10 12:37:09.595  4288 12355 E SdlTransportBroker: Unable to send message to router service. Not registered.
11-10 12:39:10.560  4288 12381 E SdlTransportBroker: Broker object null, unable to process message
11-10 12:39:10.565  4288 12104 D SdlTransportBroker: Hardware disconnected
11-10 12:39:10.567  4288 12104 D Multiplex Transport: Handling disconnect
11-10 12:39:10.567  4288 12104 D Multiplex Transport: Handle transport Error
11-10 12:39:10.633  4288 12381 E AndroidRuntime: FATAL EXCEPTION: Thread-464
11-10 12:39:10.633  4288 12381 E AndroidRuntime: Process: com.toyota.tcapp, PID: 4288
11-10 12:39:10.633  4288 12381 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.smartdevicelink.transport.TransportBroker.enableLegacyMode(boolean)' on a null object reference
11-10 12:39:10.633  4288 12381 E AndroidRuntime:        at com.smartdevicelink.transport.TransportBroker$ClientHandler.handleMessage(SourceFile:155)
11-10 12:39:10.633  4288 12381 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:102)
11-10 12:39:10.633  4288 12381 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:135)
11-10 12:39:10.633  4288 12381 E AndroidRuntime:        at com.smartdevicelink.transport.MultiplexTransport$TransportBrokerThread.run(SourceFile:230)
11-10 12:39:22.486  4288 12381 I Process : Sending signal. PID: 4288 SIG: 9
11-10 12:39:22.577   797   813 I ActivityManager: Process com.toyota.tcapp (pid 4288) has died
```

**Comment by joeygrover** [comment]
Fixed with #364
