### ISSUE TITLE
java.lang.OutOfMemoryError when allocating byte array in SdlPsm.java

### ISSUE THREAD

**Issue by askirk** [smartdevicelink/sdl_android#375]
Spotify reported a few occurances of OOM errors and provided the following stacktrace:

```
Fatal Exception: java.lang.OutOfMemoryError
       at com.spotify.music.internal.crashes.SpotifyExceptionHandler.processOutOfMemory(SourceFile:1054)
       at com.spotify.music.internal.crashes.SpotifyCrashlyticsCrashManager$3.uncaughtException(SourceFile:81)
       at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:693)
       at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:690)
Caused by java.lang.OutOfMemoryError: Failed to allocate a 1769173877 byte allocation with 4194304 free bytes and 251MB until OOM
       at com.smartdevicelink.transport.SdlPsm.transitionOnInput(SourceFile:156)
       at com.smartdevicelink.transport.SdlPsm.handleByte(SourceFile:54)
       at com.smartdevicelink.transport.MultiplexBluetoothTransport$ConnectedThread.run(SourceFile:795)
```

This issue relates to spotify crash numbers 722722 and 711556 and occurs in https://github.com/smartdevicelink/sdl_android/blob/master/sdl_android_lib/src/com/smartdevicelink/transport/SdlPsm.java#L199

**Comment by askirk** [comment]
L199 has been surrounded with try/catch since version 4.2.1
