### ISSUE TITLE
Process does not have BLUETOOTH permission: java.lang.SecurityException

### ISSUE THREAD

**Issue by askirk** [smartdevicelink/sdl_android#376]
Error

`Caused by java.lang.SecurityException: Need BLUETOOTH permission: Neither user 10227 nor current process has android.permission.BLUETOOTH.
       at android.os.Parcel.readException(Parcel.java:1620)
       at android.os.Parcel.readException(Parcel.java:1573)
       at android.bluetooth.IBluetooth$Stub$Proxy.getState(IBluetooth.java:1291)
       at android.bluetooth.BluetoothAdapter.getState(BluetoothAdapter.java:1086)
       at com.smartdevicelink.transport.SdlRouterService$3.onReceive(SourceFile:279)` 

was reported. It occured at

https://github.com/smartdevicelink/sdl_android/blob/master/sdl_android_lib/src/com/smartdevicelink/transport/SdlRouterService.java#L279

The following permissions should already be in the App Manifest for the app, need to investigate why they weren't in this instance.
```
<uses-permission android:name="android.permission.BLUETOOTH" />
<uses-permission android:name="android.permission.BLUETOOTH_ADMIN" />
```

**Comment by askirk** [comment]
https://developer.android.com/training/permissions/requesting.html#perm-check

**Comment by askirk** [comment]
https://developer.android.com/reference/android/support/v4/content/ContextCompat.html#checkSelfPermission%28android.content.Context,%20java.lang.String%29
