### ISSUE TITLE
Failed Resolution of ComponentName class (Landroid/content/ComponentName)

### ISSUE THREAD

**Issue by askirk** [smartdevicelink/sdl_android#377]
Stacktrace:

```
Fatal Exception: java.lang.NoClassDefFoundError: Failed resolution of: Landroid/content/ComponentName;
       at com.smartdevicelink.transport.SdlRouterService.onCreate(SourceFile:786)
...
Caused by java.lang.ClassNotFoundException: Didn't find class "android.content.ComponentName" on path: DexPathList[]
       at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
       at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
       at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
       at com.smartdevicelink.transport.SdlRouterService.onCreate(SourceFile:786)
```

Occurs at https://github.com/smartdevicelink/sdl_android/blob/master/sdl_android_lib/src/com/smartdevicelink/transport/SdlRouterService.java#L786
ComponentName object couldn't be resolved.

**Comment by askirk** [comment]
http://stackoverflow.com/questions/19523167/android-classnotfoundexception-didnt-find-class-on-path
Could it be due to a conflict in android support library version between app and the sdl library?

**Comment by joeygrover** [comment]
Issue was only reported on 2 devices. SDL Android lib does not contain or use support libraries. Marking as won't fix.
