### ISSUE TITLE
NPE in SdlRouterService.bluetoothAvailable() : BluetoothAdapter.getDefaultAdapter().isEnabled() call

### ISSUE THREAD

**Issue by askirk** [smartdevicelink/sdl_android#378]
Stacktrace:

```
Caused by java.lang.NullPointerException
       at android.os.Parcel.readException(Parcel.java:1493)
       at android.os.Parcel.readException(Parcel.java:1436)
       at android.bluetooth.IBluetooth$Stub$Proxy.isEnabled(IBluetooth.java:596)
       at android.bluetooth.BluetoothAdapter.isEnabled(BluetoothAdapter.java:452)
       at com.smartdevicelink.transport.SdlRouterService.bluetoothAvailable(SourceFile:1027)
       at com.smartdevicelink.transport.SdlRouterService.shouldServiceRemainOpen(SourceFile:1051)
       at com.smartdevicelink.transport.SdlRouterService.onStartCommand(SourceFile:868)
```

Snippet in question:

```
private boolean bluetoothAvailable(){
		boolean retVal = (!(BluetoothAdapter.getDefaultAdapter()==null) && BluetoothAdapter.getDefaultAdapter().isEnabled());
		//Log.d(TAG, "Bluetooth Available? - " + retVal);
		return retVal;
}
```

The exception is raised within the isEnabled method, and it is not an error due to invoking a method on a null object reference. (BluetoothAdapter.getDefaultAdapter() is not null.)

**Comment by askirk** [comment]
Proposed replacement:
```
private boolean bluetoothAvailable(){
		boolean retVal = (BluetoothAdapter.getDefaultAdapter() != null) ? BluetoothAdapter.getDefaultAdapter().isEnabled() : false;
		//Log.d(TAG, "Bluetooth Available? - " + retVal);
		return retVal;
}
```

**Comment by askirk** [comment]
This could relate to #376

**Comment by askirk** [comment]
Could try/catch for NPE, return false if we get the exception
