### ISSUE TITLE
NPEs in SdlRouterService.processCheck()

### ISSUE THREAD

**Issue by askirk** [smartdevicelink/sdl_android#379]
*Issue 1*

Stacktrace:

```
Fatal Exception: java.lang.RuntimeException: Unable to create service smartdevicelink.service.SdlRouterService: java.lang.NullPointerException: Attempt to invoke interface method 'java.util.Iterator java.util.List.iterator()' on a null object reference
       at android.app.ActivityThread.handleCreateService(ActivityThread.java:2878)
       at android.app.ActivityThread.access$2200(ActivityThread.java:152)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1434)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:135)
       at android.app.ActivityThread.main(ActivityThread.java:5538)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:960)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
Caused by java.lang.NullPointerException: Attempt to invoke interface method 'java.util.Iterator java.util.List.iterator()' on a null object reference
       at com.smartdevicelink.transport.SdlRouterService.processCheck(SourceFile:2765)
```

Occurs at https://github.com/smartdevicelink/sdl_android/blob/master/sdl_android_lib/src/com/smartdevicelink/transport/SdlRouterService.java#L765

`ActivityManager am.getRunningAppProcesses()` is null here.

*Issue 2*

Stacktrace:
```
Fatal Exception: java.lang.RuntimeException: Unable to create service service.SdlRouterService: java.lang.NullPointerException: Attempt to read from field 'int android.app.ActivityManager$RunningAppProcessInfo.pid' on a null object reference
       at android.app.ActivityThread.handleCreateService(ActivityThread.java:3281)
       at android.app.ActivityThread.access$1900(ActivityThread.java:181)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1558)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:145)
       at android.app.ActivityThread.main(ActivityThread.java:6126)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)
Caused by java.lang.NullPointerException: Attempt to read from field 'int android.app.ActivityManager$RunningAppProcessInfo.pid' on a null object reference
       at com.smartdevicelink.transport.SdlRouterService.processCheck(SourceFile:2767)
```

Occurs at https://github.com/smartdevicelink/sdl_android/blob/master/sdl_android_lib/src/com/smartdevicelink/transport/SdlRouterService.java#L767

`processInfo` is null.

**Comment by askirk** [comment]
Proposal is to check that both `am` and `processInfo` is not null before they are used.
