### ISSUE TITLE
NPE in SdlBroadCastReceiver.isRouterServiceRunning()

### ISSUE THREAD

**Issue by askirk** [smartdevicelink/sdl_android#381]
Stacktrace:

```
Fatal Exception: java.lang.RuntimeException: Unable to bind to service com.spotify.mobile.android.service.SpotifyService@1cf86fa8 with Intent { cmp=com.spotify.music/com.spotify.mobile.android.service.SpotifyService }: java.lang.NullPointerException: Attempt to read from field 'android.content.ComponentName com.android.server.am.ServiceRecord.name' on a null object reference
       at android.app.ActivityThread.handleBindService(ActivityThread.java:2787)
       at android.app.ActivityThread.access$1900(ActivityThread.java:147)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1369)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:135)
       at android.app.ActivityThread.main(ActivityThread.java:5253)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:900)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:695)
Caused by java.lang.NullPointerException: Attempt to read from field 'android.content.ComponentName com.android.server.am.ServiceRecord.name' on a null object reference
       at android.os.Parcel.readException(Parcel.java:1546)
       at android.os.Parcel.readException(Parcel.java:1493)
       at android.app.ActivityManagerProxy.getServices(ActivityManagerNative.java:3091)
       at android.app.ActivityManager.getRunningServices(ActivityManager.java:1579)
       at com.smartdevicelink.transport.SdlBroadcastReceiver.isRouterServiceRunning(SourceFile:201)
```

Error occurs at
https://github.com/smartdevicelink/sdl_android/blob/master/sdl_android_lib/src/com/smartdevicelink/transport/SdlBroadcastReceiver.java#L196

**Comment by askirk** [comment]
Proposed solution:
Wrap the inside of for loop with
`if (service != null)`

*may want to also check that ActivityManager that is grabbed is not null

**Comment by askirk** [comment]
grab the list and do a regular for loop
