### ISSUE TITLE
NPE in MultiplexBluetoothTransport.ConnectedThread.cancel() : mmInStream

### ISSUE THREAD

**Issue by askirk** [smartdevicelink/sdl_android#382]
Stacktrace:

```
Fatal Exception: java.lang.NullPointerException
       at android.bluetooth.BluetoothSocket.close(BluetoothSocket.java:465)
       at android.bluetooth.BluetoothInputStream.close(BluetoothInputStream.java:44)
       at com.smartdevicelink.transport.MultiplexBluetoothTransport$ConnectedThread.cancel(SourceFile:822)
       at com.smartdevicelink.transport.MultiplexBluetoothTransport.stop(SourceFile:290)
       at com.smartdevicelink.transport.MultiplexBluetoothTransport.stop(SourceFile:280)
       at com.smartdevicelink.transport.MultiplexBluetoothTransport.connectionLost(SourceFile:3348)
```

Occurs at https://github.com/smartdevicelink/sdl_android/blob/master/sdl_android_lib/src/com/smartdevicelink/transport/MultiplexBluetoothTransport.java#L822.

The if statement evaluates to true, and the value of mmInStream is set to null (assuming it is closed by some other cancel() call) before the inside of the if statement is executed.

**Comment by askirk** [comment]
Propsal is to catch NPE as well as IOException in the catch block. Comment to specify that the purpose is to protect for mmInStream and no other variable.
