### ISSUE TITLE
NPE at MultiplexTransport.TransportBrokerThread.cancel() : threadLooper

### ISSUE THREAD

**Issue by askirk** [smartdevicelink/sdl_android#385]
Stacktrace:

```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.os.Looper.quitSafely()' on a null object reference
       at com.smartdevicelink.transport.MultiplexTransport$TransportBrokerThread.cancel(SourceFile:180)
       at com.smartdevicelink.transport.MultiplexTransport.handleTransportError(SourceFile:116)
       at com.smartdevicelink.transport.MultiplexTransport$TransportBrokerThread$1.onLegacyModeEnabled(SourceFile:287)
       at com.smartdevicelink.transport.TransportBroker$ClientHandler.handleMessage(SourceFile:256)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:158)
       at com.smartdevicelink.transport.MultiplexTransport$TransportBrokerThread.run(SourceFile:230)
```

Occurs at 
https://github.com/smartdevicelink/sdl_android/blob/master/sdl_android_lib/src/com/smartdevicelink/transport/MultiplexTransport.java#L180

threadLooper is null in this case.

**Comment by askirk** [comment]
Proposal is to wrap code in cancel with `synchronized(this)` (variable lock)
