### ISSUE TITLE
OOM error at BinaryFrameHeader.parseBinaryHeader()

### ISSUE THREAD

**Issue by askirk** [smartdevicelink/sdl_android#388]
Stacktrace:
```
Fatal Exception: java.lang.OutOfMemoryError
       at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:693)
       at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:690)
Caused by java.lang.OutOfMemoryError: Failed to allocate a 1768254576 byte allocation with 8388608 free bytes and 224MB until OOM
       at com.smartdevicelink.protocol.BinaryFrameHeader.parseBinaryHeader(SourceFile:32)
       at com.smartdevicelink.protocol.WiProProtocol$MessageFrameAssembler.notifyIfFinished(SourceFile:1283)
       at com.smartdevicelink.protocol.WiProProtocol$MessageFrameAssembler.handleMultiFrameMessageFrame(SourceFile:312)
       at com.smartdevicelink.protocol.WiProProtocol$MessageFrameAssembler.handleFrame(SourceFile:348)
       at com.smartdevicelink.protocol.WiProProtocol.handlePacketReceived(SourceFile:226)
       at com.smartdevicelink.SdlConnection.SdlConnection.onTransportPacketReceived(SourceFile:207)
```

Occurs at https://github.com/smartdevicelink/sdl_android/blob/master/sdl_android_lib/src/com/smartdevicelink/protocol/BinaryFrameHeader.java#L32

1.76 GB data size requested!

Question: what device was being used?

**Comment by askirk** [comment]
`parseBinaryHeader` is called in 3 different places.
https://github.com/smartdevicelink/sdl_android/blob/develop/sdl_android_lib/src/com/smartdevicelink/protocol/WiProProtocol.java#L283
https://github.com/smartdevicelink/sdl_android/blob/develop/sdl_android_lib/src/com/smartdevicelink/protocol/WiProProtocol.java#L431
https://github.com/smartdevicelink/sdl_android/blob/develop/sdl_android_lib/src/com/smartdevicelink/transport/SdlRouterService.java#L1423
