### ISSUE TITLE
NPE in HttpRequestTask.doInBackground()

### ISSUE THREAD

**Issue by askirk** [smartdevicelink/sdl_android#390]
Stacktrace:

```
Caused by java.lang.NullPointerException
       at org.apache.harmony.xnet.provider.jsse.OpenSSLSocketFactoryImpl.createSocket(OpenSSLSocketFactoryImpl.java:94)
       at libcore.net.http.HttpConnection.setupSecureSocket(HttpConnection.java:197)
       at libcore.net.http.HttpsURLConnectionImpl$HttpsEngine.makeSslConnection(HttpsURLConnectionImpl.java:478)
       at libcore.net.http.HttpsURLConnectionImpl$HttpsEngine.connect(HttpsURLConnectionImpl.java:433)
       at libcore.net.http.HttpEngine.sendSocketRequest(HttpEngine.java:289)
       at libcore.net.http.HttpEngine.sendRequest(HttpEngine.java:239)
       at libcore.net.http.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:80)
       at libcore.net.http.HttpURLConnectionImpl.getOutputStream(HttpURLConnectionImpl.java:188)
       at libcore.net.http.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:281)
       at com.smartdevicelink.util.HttpRequestTask.doInBackground(SourceFile:88)
       at com.smartdevicelink.util.HttpRequestTask.doInBackground(SourceFile:16)
```

Occurs at https://github.com/smartdevicelink/sdl_android/blob/master/sdl_android_lib/src/com/smartdevicelink/util/HttpRequestTask.java#L88

NPE happens deep into getOutputStream() call. Unsure of the cause.

**Comment by askirk** [comment]
http://stackoverflow.com/questions/20817383/url-openstream-or-urlconnection-getinputstream-raise-nullpointerexception-on

**Comment by askirk** [comment]
Possibly call `.connect()` before the IF statement?
