### ISSUE TITLE
java.lang.SecurityException starting Service in SdlBroadcastReceiver.OnReceive.WakeupRouterService()

### ISSUE THREAD

**Issue by askirk** [smartdevicelink/sdl_android#391]
Stacktrace:
```
Caused by java.lang.SecurityException: Unable to start service Intent { smartdevicelink.service.SdlRouterService }: Unable to launch app for service Intent { cmp=smartdevicelink.service.SdlRouterService }: process is bad
       at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1887)
       at android.app.ContextImpl.startService(ContextImpl.java:1860)
       at android.content.ContextWrapper.startService(ContextWrapper.java:516)
       at android.content.ContextWrapper.startService(ContextWrapper.java:516)
       at com.smartdevicelink.transport.SdlBroadcastReceiver.wakeUpRouterService(SourceFile:166)
       at com.smartdevicelink.transport.SdlBroadcastReceiver.onReceive(SourceFile:141)
```

Occurs at https://github.com/smartdevicelink/sdl_android/blob/master/sdl_android_lib/src/com/smartdevicelink/transport/SdlBroadcastReceiver.java#L161

Unsure of what `process is bad` means in this case.

**Comment by askirk** [comment]
http://stackoverflow.com/questions/3253676/how-to-fix-process-is-bad-error-for-an-android-widget
This said there is bad persistent data and the only way to fix is uninstall/reinstall and reboot phone...

**Comment by joeygrover** [comment]
I believe that is true for the particular user, however, to fix in the library it seems another answer on that SO post mentions it happens from not handling an exception in the BR too many times so the OS takes measures to prevent it from happening.
