### ISSUE TITLE
java.lang.SecurityException starting Service in SdlBroadcastReceiver.OnReceive.isRouterServiceRunning()

### ISSUE THREAD

**Issue by askirk** [smartdevicelink/sdl_android#392]
Stacktrace:

```
Caused by java.lang.SecurityException: Unable to start service Intent { cmp=smartdevicelink.service.SdlRouterService (has extras) }: Unable to launch app for service Intent { cmp=smartdevicelink.service.SdlRouterService }: process is bad
       at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1358)
       at android.app.ContextImpl.startService(ContextImpl.java:1306)
       at android.content.ContextWrapper.startService(ContextWrapper.java:606)
       at android.content.ContextWrapper.startService(ContextWrapper.java:606)
       at com.smartdevicelink.transport.SdlBroadcastReceiver.isRouterServiceRunning(SourceFile:211)
       at com.smartdevicelink.transport.SdlBroadcastReceiver.wakeUpRouterService(SourceFile:157)
       at com.smartdevicelink.transport.SdlBroadcastReceiver.onReceive(SourceFile:141)
```

Occurs at https://github.com/smartdevicelink/sdl_android/blob/master/sdl_android_lib/src/com/smartdevicelink/transport/SdlBroadcastReceiver.java#L206

It may be useful to look at Manifest file.

**Comment by askirk** [comment]
Add try/catch and bail if we get the exception.
