### ISSUE TITLE
Fix packetizer unit tests

### ISSUE THREAD

**Issue by Tnnnguyen** [smartdevicelink/sdl_android#529]
Currently the packetizer unit test test cases are failing _intermittently_ in the testConstructor method for AbstractPacketizerTests.java, StreamPacketizerTests.java and StreamRPCPacketizerTests.java.

The reason is that this method needs an InputStream and we have been getting the stream from "https://github.com/smartdevicelink/sdl_android". 

But what we really need is just an arbitrary but valid InputStream object. There is no need to make it more complicated unnecessarily by connecting to an external source to get an InputStream as the connection sometimes fails, times out, resulting in an IOException and consequently fails the test cases.

This issue will fix the problem by getting an InputStream object locally.

Connection times out here:
```
testInputStream = new BufferedInputStream(urlConnection.getInputStream());
```
[AbstractPacketizerTests](https://github.com/smartdevicelink/sdl_android/blob/master/sdl_android/src/androidTest/java/com/smartdevicelink/test/streaming/AbstractPacketizerTests.java#L52)
[StreamPacketizerTests](https://github.com/smartdevicelink/sdl_android/blob/master/sdl_android/src/androidTest/java/com/smartdevicelink/test/streaming/StreamPacketizerTests.java#L45)
[StreamRPCPacketizerTests](https://github.com/smartdevicelink/sdl_android/blob/master/sdl_android/src/androidTest/java/com/smartdevicelink/test/streaming/StreamRPCPacketizerTests.java#L48)

Failed tests:
```
com.smartdevicelink.test.streaming.AbstractPacketizerTests > testConstructors[test(AVD) - 5.0.2] FAILED 
	junit.framework.AssertionFailedError: IOException was thrown.
	at junit.framework.Assert.fail(Assert.java:50)
com.smartdevicelink.test.streaming.StreamPacketizerTests > testConstructor[test(AVD) - 5.0.2] FAILED 
	junit.framework.AssertionFailedError: IOException was thrown.
	at junit.framework.Assert.fail(Assert.java:50)
com.smartdevicelink.test.streaming.StreamRPCPacketizerTests > testConstructor[test(AVD) - 5.0.2] FAILED 
	junit.framework.AssertionFailedError: IOException was thrown.
	at junit.framework.Assert.fail(Assert.java:50)
```

Log:
```
05-25 10:14:16.522 4842-4857/com.smartdevicelink.test W/System.err: java.net.ConnectException: failed to connect to github.com/192.30.253.113 (port 443): connect failed: ETIMEDOUT (Connection timed out)
05-25 10:14:16.524 4842-4857/com.smartdevicelink.test W/System.err:     at libcore.io.IoBridge.connect(IoBridge.java:124)
05-25 10:14:16.524 4842-4857/com.smartdevicelink.test W/System.err:     at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:183)
05-25 10:14:16.525 4842-4857/com.smartdevicelink.test W/System.err:     at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:452)
05-25 10:14:16.525 4842-4857/com.smartdevicelink.test W/System.err:     at java.net.Socket.connect(Socket.java:884)
05-25 10:14:16.525 4842-4857/com.smartdevicelink.test W/System.err:     at com.android.okhttp.internal.Platform.connectSocket(Platform.java:117)
05-25 10:14:16.525 4842-4857/com.smartdevicelink.test W/System.err:     at com.android.okhttp.internal.http.SocketConnector.connectRawSocket(SocketConnector.java:160)
05-25 10:14:16.525 4842-4857/com.smartdevicelink.test W/System.err:     at com.android.okhttp.internal.http.SocketConnector.connectTls(SocketConnector.java:79)
05-25 10:14:16.526 4842-4857/com.smartdevicelink.test W/System.err:     at com.android.okhttp.Connection.connect(Connection.java:143)
05-25 10:14:16.526 4842-4857/com.smartdevicelink.test W/System.err:     at com.android.okhttp.Connection.connectAndSetOwner(Connection.java:185)
05-25 10:14:16.526 4842-4857/com.smartdevicelink.test W/System.err:     at com.android.okhttp.OkHttpClient$1.connectAndSetOwner(OkHttpClient.java:128)
05-25 10:14:16.526 4842-4857/com.smartdevicelink.test W/System.err:     at com.android.okhttp.internal.http.HttpEngine.nextConnection(HttpEngine.java:341)
05-25 10:14:16.526 4842-4857/com.smartdevicelink.test W/System.err:     at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:330)
05-25 10:14:16.526 4842-4857/com.smartdevicelink.test W/System.err:     at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:248)
05-25 10:14:16.527 4842-4857/com.smartdevicelink.test W/System.err:     at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:437)
05-25 10:14:16.527 4842-4857/com.smartdevicelink.test W/System.err:     at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:388)
05-25 10:14:16.527 4842-4857/com.smartdevicelink.test W/System.err:     at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:231)
05-25 10:14:16.527 4842-4857/com.smartdevicelink.test W/System.err:     at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getInputStream(DelegatingHttpsURLConnection.java:210)
05-25 10:14:16.528 4842-4857/com.smartdevicelink.test W/System.err:     at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java)
05-25 10:14:16.528 4842-4857/com.smartdevicelink.test W/System.err:     at com.smartdevicelink.test.streaming.AbstractPacketizerTests.testConstructors(AbstractPacketizerTests.java:54)
05-25 10:14:16.528 4842-4857/com.smartdevicelink.test W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
05-25 10:14:16.528 4842-4857/com.smartdevicelink.test W/System.err:     at junit.framework.TestCase.runTest(TestCase.java:168)
05-25 10:14:16.528 4842-4857/com.smartdevicelink.test W/System.err:     at junit.framework.TestCase.runBare(TestCase.java:134)
05-25 10:14:16.529 4842-4857/com.smartdevicelink.test W/System.err:     at junit.framework.TestResult$1.protect(TestResult.java:115)
05-25 10:14:16.529 4842-4857/com.smartdevicelink.test W/System.err:     at android.support.test.internal.runner.junit3.AndroidTestResult.runProtected(AndroidTestResult.java:77)
05-25 10:14:16.529 4842-4857/com.smartdevicelink.test W/System.err:     at junit.framework.TestResult.run(TestResult.java:118)
05-25 10:14:16.532 4842-4857/com.smartdevicelink.test W/System.err:     at android.support.test.internal.runner.junit3.AndroidTestResult.run(AndroidTestResult.java:55)
05-25 10:14:16.532 4842-4857/com.smartdevicelink.test W/System.err:     at junit.framework.TestCase.run(TestCase.java:124)
05-25 10:14:16.532 4842-4857/com.smartdevicelink.test W/System.err:     at android.support.test.internal.runner.junit3.NonLeakyTestSuite$NonLeakyTest.run(NonLeakyTestSuite.java:63)
05-25 10:14:16.532 4842-4857/com.smartdevicelink.test W/System.err:     at junit.framework.TestSuite.runTest(TestSuite.java:243)
05-25 10:14:16.532 4842-4857/com.smartdevicelink.test W/System.err:     at junit.framework.TestSuite.run(TestSuite.java:238)
05-25 10:14:16.532 4842-4857/com.smartdevicelink.test W/System.err:     at android.support.test.internal.runner.junit3.DelegatingTestSuite.run(DelegatingTestSuite.java:103)
05-25 10:14:16.533 4842-4857/com.smartdevicelink.test W/System.err:     at android.support.test.internal.runner.junit3.AndroidTestSuite.run(AndroidTestSuite.java:69)
05-25 10:14:16.533 4842-4857/com.smartdevicelink.test W/System.err:     at android.support.test.internal.runner.junit3.JUnit38ClassRunner.run(JUnit38ClassRunner.java:103)
05-25 10:14:16.533 4842-4857/com.smartdevicelink.test W/System.err:     at org.junit.runners.Suite.runChild(Suite.java:128)
05-25 10:14:16.533 4842-4857/com.smartdevicelink.test W/System.err:     at org.junit.runners.Suite.runChild(Suite.java:27)
05-25 10:14:16.533 4842-4857/com.smartdevicelink.test W/System.err:     at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
05-25 10:14:16.534 4842-4857/com.smartdevicelink.test W/System.err:     at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
05-25 10:14:16.534 4842-4857/com.smartdevicelink.test W/System.err:     at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
05-25 10:14:16.534 4842-4857/com.smartdevicelink.test W/System.err:     at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
05-25 10:14:16.534 4842-4857/com.smartdevicelink.test W/System.err:     at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
05-25 10:14:16.534 4842-4857/com.smartdevicelink.test W/System.err:     at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
05-25 10:14:16.534 4842-4857/com.smartdevicelink.test W/System.err:     at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
05-25 10:14:16.535 4842-4857/com.smartdevicelink.test W/System.err:     at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
05-25 10:14:16.535 4842-4857/com.smartdevicelink.test W/System.err:     at android.support.test.internal.runner.TestExecutor.execute(TestExecutor.java:59)
05-25 10:14:16.535 4842-4857/com.smartdevicelink.test W/System.err:     at android.support.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:262)
05-25 10:14:16.535 4842-4857/com.smartdevicelink.test W/System.err:     at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1879)
05-25 10:14:16.536 4842-4857/com.smartdevicelink.test W/System.err: Caused by: android.system.ErrnoException: connect failed: ETIMEDOUT (Connection timed out)
05-25 10:14:16.537 4842-4857/com.smartdevicelink.test W/System.err:     at libcore.io.Posix.connect(Native Method)
05-25 10:14:16.538 4842-4857/com.smartdevicelink.test W/System.err:     at libcore.io.BlockGuardOs.connect(BlockGuardOs.java:111)
05-25 10:14:16.538 4842-4857/com.smartdevicelink.test W/System.err:     at libcore.io.IoBridge.connectErrno(IoBridge.java:137)
05-25 10:14:16.538 4842-4857/com.smartdevicelink.test W/System.err:     at libcore.io.IoBridge.connect(IoBridge.java:122)
05-25 10:14:16.538 4842-4857/com.smartdevicelink.test W/System.err: 	... 45 more
05-25 10:14:16.542 4842-4857/com.smartdevicelink.test I/TestRunner: failed: testConstructors(com.smartdevicelink.test.streaming.AbstractPacketizerTests)
05-25 10:14:16.542 4842-4857/com.smartdevicelink.test I/TestRunner: ----- begin exception -----
05-25 10:14:16.546 4842-4857/com.smartdevicelink.test I/TestRunner: junit.framework.AssertionFailedError: IOException was thrown.
                                                                        at junit.framework.Assert.fail(Assert.java:50)
                                                                        at com.smartdevicelink.test.streaming.AbstractPacketizerTests.testConstructors(AbstractPacketizerTests.java:97)
                                                                        at java.lang.reflect.Method.invoke(Native Method)
                                                                        at junit.framework.TestCase.runTest(TestCase.java:168)
                                                                        at junit.framework.TestCase.runBare(TestCase.java:134)
                                                                        at junit.framework.TestResult$1.protect(TestResult.java:115)
                                                                        at android.support.test.internal.runner.junit3.AndroidTestResult.runProtected(AndroidTestResult.java:77)
                                                                        at junit.framework.TestResult.run(TestResult.java:118)
                                                                        at android.support.test.internal.runner.junit3.AndroidTestResult.run(AndroidTestResult.java:55)
                                                                        at junit.framework.TestCase.run(TestCase.java:124)
                                                                        at android.support.test.internal.runner.junit3.NonLeakyTestSuite$NonLeakyTest.run(NonLeakyTestSuite.java:63)
                                                                        at junit.framework.TestSuite.runTest(TestSuite.java:243)
                                                                        at junit.framework.TestSuite.run(TestSuite.java:238)
                                                                        at android.support.test.internal.runner.junit3.DelegatingTestSuite.run(DelegatingTestSuite.java:103)
                                                                        at android.support.test.internal.runner.junit3.AndroidTestSuite.run(AndroidTestSuite.java:69)
                                                                        at android.support.test.internal.runner.junit3.JUnit38ClassRunner.run(JUnit38ClassRunner.java:103)
                                                                        at org.junit.runners.Suite.runChild(Suite.java:128)
                                                                        at org.junit.runners.Suite.runChild(Suite.java:27)
                                                                        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
                                                                        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
                                                                        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
                                                                        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
                                                                        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
                                                                        at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
                                                                        at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
                                                                        at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
                                                                        at android.support.test.internal.runner.TestExecutor.execute(TestExecutor.java:59)
                                                                        at android.support.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:262)
                                                                        at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1879)
05-25 10:14:16.546 4842-4857/com.smartdevicelink.test I/TestRunner: ----- end exception -----
```

**Comment by Tnnnguyen** [comment]
Completed.
