### ISSUE TITLE
NPE in MultiplexBluetoothTransport

### ISSUE THREAD

**Issue by jthrun** [smartdevicelink/sdl_android#554]
I am seeing NullPointerException from [here](https://github.com/smartdevicelink/sdl_android/blob/master/sdl_android/src/main/java/com/smartdevicelink/transport/MultiplexBluetoothTransport.java#L180)
in MultiplexBluetoothTransport.  It seems like this line in the code is doing a null check on an instance of a static variable so I'm guessing that the static variable itself is null.

Here is the stack trace:
```
07-11 10:22:24.014 15384 15384 E AndroidRuntime: java.lang.RuntimeException: Unable to start service com.main.tcapp.sdl.SdlRouterService@2052c2cb with Intent { cmp=com.toyota.tcapp/com.main.tcapp.sdl.SdlRouterService (has extras) }: java.lang.NullPointerException: Attempt to read from field 'com.smartdevicelink.transport.MultiplexBluetoothTransport$ConnectThread com.smartdevicelink.transport.MultiplexBluetoothTransport.mConnectThread' on a null object reference
07-11 10:22:24.014 15384 15384 E AndroidRuntime: 	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:2881)
07-11 10:22:24.014 15384 15384 E AndroidRuntime: 	at android.app.ActivityThread.access$2100(ActivityThread.java:144)
07-11 10:22:24.014 15384 15384 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1376)
07-11 10:22:24.014 15384 15384 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
07-11 10:22:24.014 15384 15384 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:135)
07-11 10:22:24.014 15384 15384 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:5221)
07-11 10:22:24.014 15384 15384 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
07-11 10:22:24.014 15384 15384 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Method.java:372)
07-11 10:22:24.014 15384 15384 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
07-11 10:22:24.014 15384 15384 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
07-11 10:22:24.014 15384 15384 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to read from field 'com.smartdevicelink.transport.MultiplexBluetoothTransport$ConnectThread com.smartdevicelink.transport.MultiplexBluetoothTransport.mConnectThread' on a null object reference
07-11 10:22:24.014 15384 15384 E AndroidRuntime: 	at com.smartdevicelink.transport.MultiplexBluetoothTransport.start(MultiplexBluetoothTransport.java:180)
07-11 10:22:24.014 15384 15384 E AndroidRuntime: 	at com.smartdevicelink.transport.SdlRouterService.initBluetoothSerialService(SdlRouterService.java:1132)
07-11 10:22:24.014 15384 15384 E AndroidRuntime: 	at com.smartdevicelink.transport.SdlRouterService.onStartCommand(SdlRouterService.java:899)
07-11 10:22:24.014 15384 15384 E AndroidRuntime: 	at com.main.tcapp.sdl.SdlRouterService.onStartCommand(SdlRouterService.java:237)
07-11 10:22:24.014 15384 15384 E AndroidRuntime: 	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:2864)
07-11 10:22:24.014 15384 15384 E AndroidRuntime: 	... 9 more
```

I wonder if it is due to the change that went in to fix an earlier [issue](https://github.com/smartdevicelink/sdl_android/pull/537/commits/c30dd431c8767bd772ad3139386c623846c5ba9a).   However, it happens on starting the SDL Router service.

I'm using master plus cherry-picked the commit for that fix.

**Comment by jthrun** [comment]
More info, it seems to happen when there are no more BT channels available at the point that SDLRouterService starts.

**Comment by jthrun** [comment]
I *do* think this related to the change that went in for issue 427.  Here is a related stack trace that happens when stopping rather than starting:
```
Fatal Exception: java.lang.RuntimeException: Unable to stop service com.main.tcapp.sdl.SdlRouterService@4b39e1: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.smartdevicelink.transport.MultiplexBluetoothTransport.stop(int)' on a null object reference
       at android.app.ActivityThread.handleStopService(ActivityThread.java:3725)
       at android.app.ActivityThread.-wrap30(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1738)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6646)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1468)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1358)
Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'void com.smartdevicelink.transport.MultiplexBluetoothTransport.stop(int)' on a null object reference
       at com.smartdevicelink.transport.MultiplexBluetoothTransport.stop(SourceFile:291)
       at com.smartdevicelink.transport.SdlRouterService.closeBluetoothSerialServer(SourceFile:1547)
       at com.smartdevicelink.transport.SdlRouterService.onDestroy(SourceFile:928)
       at com.main.tcapp.sdl.SdlRouterService.onDestroy(SourceFile:134)
       at android.app.ActivityThread.handleStopService(ActivityThread.java:3708)
       at android.app.ActivityThread.-wrap30(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1738)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6646)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1468)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1358)
```

I'm wondering if part of the problem is that MultiplexBluetoothTransport is implemented as a singleton but an instance of it can still be held by the router after the "singleton" instance is supposed to have been cleared.  Also, internally the class accesses instance fields both directly and through the "singleton" instance, which seems not good and it uses the "singleton" instance without checking for null, also not so good.

**Comment by joeygrover** [comment]
Refactoring the `MultiplexBluetoothTransport` class to no longer be a singleton has been long overdue. I have committed a PR #575 that has those changes. I would appreciate if you could run some extensive tests using that PR. Because it deals with the connection code it's very important that we don't make changes that adversely affect the project.

**Comment by jthrun** [comment]
Ok, I'll pull that in today and we'll try it out for our next release.

**Comment by joeygrover** [comment]
#575 has now been merged. We had multiple people test and everything went well. Closing this issue as it is no longer relevant with #575 being merged.
