### ISSUE TITLE
NPE in onReceive method of SdlBroadcastReceiver

### ISSUE THREAD

**Issue by Tnnnguyen** [smartdevicelink/sdl_android#555]
In SdlBroadcastReceiver.java, we try to access the variable `localRouterClass` at a few places. The value of this variable is supplied by the client app's defineLocalSdlRouterClass() in SdlReceiver.java.
If - for some reasons - this value is returned as null, the SDL Library can potentially crash.
[Crash here](https://github.com/smartdevicelink/sdl_android/blob/master/sdl_android/src/main/java/com/smartdevicelink/transport/SdlBroadcastReceiver.java#L143)

Log:
```
07-11 15:18:15.098 13112-13112/com.sdl.hellosdlandroid E/AndroidRuntime: FATAL EXCEPTION: main
                                                                         Process: com.sdl.hellosdlandroid, PID: 13112
                                                                         java.lang.RuntimeException: Unable to start receiver com.sdl.hellosdlandroid.SdlReceiver: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.Class.getName()' on a null object reference
                                                                             at android.app.ActivityThread.handleReceiver(ActivityThread.java:2732)
                                                                             at android.app.ActivityThread.-wrap14(ActivityThread.java)
                                                                             at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1421)
                                                                             at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                             at android.os.Looper.loop(Looper.java:148)
                                                                             at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                             at java.lang.reflect.Method.invoke(Native Method)
                                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
                                                                          Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.Class.getName()' on a null object reference
                                                                             at android.content.ComponentName.<init>(ComponentName.java:129)
                                                                             at android.content.Intent.<init>(Intent.java:4449)
                                                                             at com.smartdevicelink.transport.SdlBroadcastReceiver.wakeUpRouterService(SdlBroadcastReceiver.java:162)
                                                                             at com.smartdevicelink.transport.SdlBroadcastReceiver.onReceive(SdlBroadcastReceiver.java:120)
                                                                             at com.sdl.hellosdlandroid.SdlReceiver.onReceive(SdlReceiver.java:32)
                                                                             at android.app.ActivityThread.handleReceiver(ActivityThread.java:2725)
                                                                             at android.app.ActivityThread.-wrap14(ActivityThread.java) 
                                                                             at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1421) 
                                                                             at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                             at android.os.Looper.loop(Looper.java:148) 
                                                                             at android.app.ActivityThread.main(ActivityThread.java:5417) 
                                                                             at java.lang.reflect.Method.invoke(Native Method) 
                                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
```
This is because we can be potentially calling `wakeUpRouterService(context, false,altServiceWake );` at some point, and that method tries to access the said variable `localRouterClass` which can be null.

We should perform a null check and return immediately, effectively bypassing the whole multiplexing flow because if the router service class is null, there is no point of doing any further work on multiplex connection.

Then SdlBroadcastReceiver.java should change from: [here](https://github.com/smartdevicelink/sdl_android/blob/master/sdl_android/src/main/java/com/smartdevicelink/transport/SdlBroadcastReceiver.java#L78)
```
localRouterClass = defineLocalSdlRouterClass();
```
to:
```
if ((localRouterClass = defineLocalSdlRouterClass()) == null) {
			return;
		}
```
It's true that the variable` localRouterClass` should not be null if the client app setups the Multiplexing flow correctly but we shouldn't make this assumption.

This issue was brought up by the Android Alexa team at Amazon and confirmed by us.

**Comment by joeygrover** [comment]
This was by design actually. We used this method to ensure developers didn't return null from that method, fail fast idea. Now that we are using Android Studio we should just define the method to be `@NonNull` and complete the code changes as suggested.

**Comment by Tnnnguyen** [comment]
Closing the issue as the behavior is by design.
