### ISSUE TITLE
Random BT disconnects observed

### ISSUE THREAD

**Issue by Tnnnguyen** [smartdevicelink/sdl_android#656]
## Bug Report
- Random Bluetooth disconnects observed.
- In log number 1, IOException in MultiplexBluetoothTransport.java is seen. The BT broadcast `android.bluetooth.device.action.CLASS_CHANGED` often accompanies the disconnect together with `android.bluetooth.device.action.ACL_DISCONNECTED` but `android.bluetooth.device.action.ACL_DISCONNECTED` can happen without `android.bluetooth.device.action.CLASS_CHANGED`.

### Reproduction Steps
Unknown, typically when doing audio passthru but not necessarily always. App developer's QA team could encounter 2 or 3 times in an in-car testing session that is about a couple of hours of drive.

### Expected Behavior
App should not be randomly disconnected.

### Observed Behavior
App is randomly disconnected.

### OS & Version Information
* Android Version: 7 (Nougat) with various device brands including Samsung Galaxy 8 and Pixel 2.
* SDL Android Version: 4.3.X and 4.4.X
* Head unit v2.2

#### Log 1:
```
11-21 17:25:35.273 12578 28949 W System.err: java.io.IOException: bt socket closed, read return: -1
11-21 17:25:35.282 12578 28949 W System.err:      at android.bluetooth.BluetoothSocket.read(BluetoothSocket.java:740)
11-21 17:25:35.282 12578 28949 W System.err:      at android.bluetooth.BluetoothInputStream.read(BluetoothInputStream.java:96)
11-21 17:25:35.282 12578 28949 W System.err:      at java.io.InputStream.read(InputStream.java:101)
11-21 17:25:35.282 12578 28949 W System.err:      at com.smartdevicelink.transport.MultiplexBluetoothTransport$ConnectedThread.run(MultiplexBluetoothTransport.java:783)
11-21 17:25:35.285 12578 28949 D Bluetooth Transport: Write Thread: socket closed
11-21 17:25:35.286 12578 28949 D Bluetooth Transport: 3 Socket Type Secure cancel
11-21 17:25:35.291 12578 12578 I Sdl Router Service: Starting bluetooth transport
11-21 17:25:35.300 12578 12578 D BluetoothSocket: bindListen(): myUserId = 0
11-21 17:25:35.300 12578 12578 W BluetoothAdapter: getBluetoothService() called with no BluetoothManagerCallback
11-21 17:25:35.331 12578 12578 E Sdl Router Service: Notifying client service of hardware disconnect.
11-21 17:25:35.331 12578  5835 D Bluetooth Transport: Socket Type: Secure BEGIN mAcceptThreadThread[Thread-37,5,main]
11-21 17:25:35.331 12578  5835 D Bluetooth Transport: SDL Bluetooth Accept thread is running.
11-21 17:25:35.362 12578 12578 D Sdl Router Service: Notifying 2 clients
11-21 17:25:35.363 12578 12578 D Sdl Router Service: Disconnect received. Action: android.bluetooth.device.action.ACL_DISCONNECTED
11-21 17:25:35.364 17510 28956 D SdlTransportBroker: Hardware disconnected
11-21 17:25:35.364 17510 28565 D SdlTransportBroker: Hardware disconnected
11-21 17:25:35.377 17510 28565 D Multiplex Transport: Handling disconnect
11-21 17:25:35.378 17510 28565 D Multiplex Transport: Handle transport Error
11-21 17:25:35.380 17510 28956 D Multiplex Transport: Handling disconnect
11-21 17:25:35.380 17510 28956 D Multiplex Transport: Handle transport Error
11-21 17:25:35.380 17510 28956 I SdlTransportBroker: Attempting to unregister with Sdl Router Service
11-21 17:25:35.380 17510 28956 W SdlTransportBroker: Unable to unregister, not bound to router service
11-21 17:25:35.380 17510 28956 W SdlTransportBroker: Unable to unbind from router service, context was null
11-21 17:25:35.383 17510 28956 E SdlProxy: VERSION-INFO: Transport failure:
11-21 17:25:35.394 12578 12578 D Sdl Router Service: Disconnect received. Action: android.bluetooth.device.action.CLASS_CHANGED
11-21 17:25:35.415 17510 28956 W SdlConnection: SDL Router service is valid; attempting to connect
11-21 17:25:35.416 17510 28956 D Multiplex Transport: Open connection
11-21 17:25:35.428 17510 28953 I SdlApplicationManager: Disconnected for reason: TRANSPORT_ERROR
11-21 17:25:35.428 17510 28953 I SdlApplicationManager: com.smartdevicelink.exception.SdlException: Sdl Proxy Cycled
11-21 17:25:35.428 17510 28953 I SdlApplicationManager: SdlExceptionCause: SDL_PROXY_CYCLED
```

#### Log 2:
```
11-21 16:02:17.108 12578 12578 D Sdl Router Service: Disconnect received. Action: android.bluetooth.device.action.ACL_DISCONNECTED
11-21 16:02:17.108 10780 30791 D SdlTransportBroker: Hardware disconnected
11-21 16:02:17.113 10780 10793 W MessageQueue: Handler (com.smartdevicelink.transport.TransportBroker$ClientHandler) {34d3090} sending message to a Handler on a dead thread
11-21 16:02:17.113 10780 10793 W MessageQueue: java.lang.IllegalStateException: Handler (com.smartdevicelink.transport.TransportBroker$ClientHandler) {34d3090} sending message to a Handler on a dead thread
11-21 16:02:17.113 10780 10793 W MessageQueue:              at android.os.MessageQueue.enqueueMessage(MessageQueue.java:543)
11-21 16:02:17.113 10780 10793 W MessageQueue:              at android.os.Handler.enqueueMessage(Handler.java:643)
11-21 16:02:17.113 10780 10793 W MessageQueue:              at android.os.Handler.sendMessageAtTime(Handler.java:612)
11-21 16:02:17.113 10780 10793 W MessageQueue:              at android.os.Handler.sendMessageDelayed(Handler.java:582)
11-21 16:02:17.113 10780 10793 W MessageQueue:              at android.os.Handler.sendMessage(Handler.java:519)
11-21 16:02:17.113 10780 10793 W MessageQueue:              at android.os.Handler$MessengerImpl.send(Handler.java:733)
11-21 16:02:17.113 10780 10793 W MessageQueue:              at android.os.IMessenger$Stub.onTransact(IMessenger.java:56)
11-21 16:02:17.113 10780 10793 W MessageQueue:              at android.os.Binder.execTransact(Binder.java:573)
11-21 16:02:17.117 10780 30791 D Multiplex Transport: Handling disconnect
11-21 16:02:17.117 10780 30791 D Multiplex Transport: Handle transport Error
11-21 16:02:17.117 10780 30791 I SdlTransportBroker: Attempting to unregister with Sdl Router Service
11-21 16:02:17.117 10780 30791 W SdlTransportBroker: Unable to unregister, not bound to router service
11-21 16:02:17.117 10780 30791 W SdlTransportBroker: Unable to unbind from router service, context was null
11-21 16:02:17.118 10780 30791 E SdlProxy: VERSION-INFO: Transport failure:
11-21 16:02:17.126 12578 12578 D Sdl Router Service: Disconnect received. Action: android.bluetooth.device.action.CLASS_CHANGED
11-21 16:02:17.143 10780 30791 W SdlConnection: SDL Router service is valid; attempting to connect
11-21 16:02:17.144 10780 30791 D Multiplex Transport: Open connection
11-21 16:02:17.146 10780 30788 I SdlApplicationManager: Disconnected for reason: TRANSPORT_ERROR
11-21 16:02:17.146 10780 30788 I SdlApplicationManager: com.smartdevicelink.exception.SdlException: Sdl Proxy Cycled
```

#### Log 3:
```
1-21 15:05:59.450 12578 12578 D Sdl Router Service: Disconnect received. Action: android.bluetooth.device.action.ACL_DISCONNECTED
11-21 15:05:59.450 10780 20858 D SdlTransportBroker: Hardware disconnected
11-21 15:05:59.454 12578 12578 D Sdl Router Service: Unbind being called.
11-21 15:05:59.455 10780 20858 D Multiplex Transport: Handling disconnect
11-21 15:05:59.455 10780 20858 D Multiplex Transport: Handle transport Error
11-21 15:05:59.456 10780 20858 I SdlTransportBroker: Attempting to unregister with Sdl Router Service
11-21 15:05:59.456 10780 20858 W SdlTransportBroker: Unable to unregister, not bound to router service
11-21 15:05:59.456 10780 20858 W SdlTransportBroker: Unable to unbind from router service, context was null
11-21 15:05:59.458 10780 20858 E SdlProxy: VERSION-INFO: Transport failure:
11-21 15:05:59.488 10780 20858 W SdlConnection: SDL Router service is valid; attempting to connect
11-21 15:05:59.489 10780 20858 D Multiplex Transport: Open connection
11-21 15:05:59.490 12578 12578 D Sdl Router Service: Disconnect received. Action: android.bluetooth.device.action.CLASS_CHANGED
11-21 15:05:59.493 10780 20855 I SdlApplicationManager: Disconnected for reason: TRANSPORT_ERROR
11-21 15:05:59.493 10780 20855 I SdlApplicationManager: com.smartdevicelink.exception.SdlException: Sdl Proxy Cycled
11-21 15:05:59.493 10780 20855 I SdlApplicationManager: SdlExceptionCause: SDL_PROXY_CYCLED
```

#### Log 4:
```
11-21 19:25:59.217  7398  9457 E SdlProxy: VERSION-INFO: Transport failure:
11-21 19:25:59.223  8938  8938 D Sdl Router Service: Unbind being called.
11-21 19:25:59.224  8938  8938 D Sdl Router Service: Disconnect received. Action: android.bluetooth.device.action.ACL_DISCONNECTED
11-21 19:25:59.230  7398  9457 W SdlConnection: SDL Router service is valid; attempting to connect
11-21 19:25:59.231  7398  9457 D Multiplex Transport: Open connection
11-21 19:25:59.233  7398  9454 I SdlApplicationManager: Disconnected for reason: TRANSPORT_ERROR
11-21 19:25:59.233  7398  9454 I SdlApplicationManager: com.smartdevicelink.exception.SdlException: Sdl Proxy Cycled
11-21 19:25:59.233  7398  9454 I SdlApplicationManager: SdlExceptionCause: SDL_PROXY_CYCLED
11-21 19:25:59.233  7398  9454 I SdlApplicationManager:    at com.smartdevicelink.proxy.SdlProxyBase.cycleProxy(SdlProxyBase.java:1491)
11-21 19:25:59.233  7398  9454 I SdlApplicationManager:    at com.smartdevicelink.proxy.SdlProxyBase$SdlInterfaceBroker.onTransportError(SdlProxyBase.java:375)
11-21 19:25:59.233  7398  9454 I SdlApplicationManager:    at com.smartdevicelink.SdlConnection.SdlSession.onTransportError(SdlSession.java:522)
11-21 19:25:59.233  7398  9454 I SdlApplicationManager:    at com.smartdevicelink.SdlConnection.SdlConnection$InternalMsgDispatcher.onTransportError(SdlConnection.java:389)
11-21 19:25:59.233  7398  9454 I SdlApplicationManager:    at com.smartdevicelink.SdlConnection.SdlConnection.onTransportError(SdlConnection.java:241)
11-21 19:25:59.233  7398  9454 I SdlApplicationManager:    at com.smartdevicelink.transport.SdlTransport.handleTransportError(SdlTransport.java:106)
11-21 19:25:59.233  7398  9454 I SdlApplicationManager:    at com.smartdevicelink.transport.MultiplexTransport.handleTransportError(MultiplexTransport.java:121)
11-21 19:25:59.233  7398  9454 I SdlApplicationManager:    at com.smartdevicelink.transport.MultiplexTransport$TransportBrokerThread$1.onHardwareDisconnected(MultiplexTransport.java:274)
11-21 19:25:59.233  7398  9454 I SdlApplicationManager:    at com.smartdevicelink.transport.TransportBroker$ClientHandler.handleMessage(TransportBroker.java:267)
11-21 19:25:59.233  7398  9454 I SdlApplicationManager:    at android.os.Handler.dispatchMessage(Handler.java:102)
11-21 19:25:59.233  7398  9454 I SdlApplicationManager:    at android.os.Looper.loop(Looper.java:154)
11-21 19:25:59.233  7398  9454 I SdlApplicationManager:    at com.smartdevicelink.transport.MultiplexTransport$TransportBrokerThread.run(MultiplexTransport.java:231)
11-21 19:25:59.234  7398  9454 D Multiplex Transport: Close connection
```

**Comment by Tnnnguyen** [comment]
Closing this issue as it is likely the result of the app developer handling their own http exception that potentially corrupts the input stream in `MultiplexBluetoothTransport` resulting in an IOException in the library (developer did not confirm but has not raised more related issue since).
